-- Site   : Programmers
-- Title  : 자동차 대여 기록 별 대여 금액 구하기 (LEVEL 4)
-- Link   : https://school.programmers.co.kr/learn/courses/30/lessons/151141
-- Date   : 2026-01-02

SELECT H.HISTORY_ID, C.DAILY_FEE FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
JOIN (SELECT 
      CAR_TYPE,
      CAST(REGEXP_REPLACE(DURATION_TYPE, '[^0-9]', '') AS UNSIGNED) AS DURATION,
      DISCOUNT_RATE
      FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN) P ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_TYPE = '트럭'
    AND DATEDIFF(END_DATE, START_DATE) + 1 = P.DURATION
GROUP BY H.HISTORY_ID
ORDER BY HISTORY_ID DESC, FEE DESC;

-- 오답 CAST 문제인 것 같음 다시 풀기
