name: Daily Close (mark ❌ for missing)
on:
  schedule:
    - cron: '5 15 * * *'        # 매일 00:05 KST (UTC+9 → 15:05)
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  close:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: refs/heads/develop           # ← develop 대상으로 작업

      # ...여기에 "⬜ → ❌" 갱신 JS 스텝(그대로 사용)...

      # 보호 브랜치이므로 PR만 생성
      - name: PR to develop
        uses: peter-evans/create-pull-request@v6
        with:
          base: develop
          branch: automation/daily-close
          title: "chore: daily close (mark ❌)"
          commit-message: "chore: daily close (mark ❌)"
