name: Daily Close (mark ❌ for missing)
on:
  schedule:
    - cron: '5 15 * * *'   # 매일 00:05 KST (UTC 15:05)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  close:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Seoul
      START_DATE: '2025-10-03'
      END_DATE:   '2025-11-21'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');

            const readme = 'README.md';
            let md = fs.readFileSync(readme, 'utf8');

            const START_TAG='<!-- PROGRESS:START -->';
            const END_TAG='<!-- PROGRESS:END -->';
            const s = md.indexOf(START_TAG), e = md.indexOf(END_TAG);
            if (s === -1 || e === -1) core.setFailed('Progress markers not found in README');

            // 어제 날짜(KST)
            const nowUtc = new Date();
            const nowKst = new Date(nowUtc.getTime() + 9*3600*1000);
            const y = new Date(nowKst);
            y.setDate(y.getDate()-1);
            const key = y.toISOString().slice(0,10);

            const block = md.slice(s + START_TAG.length, e);
            const lines = block.trim().split('\n');

            const header = '| Date | Status | Note |\n|------|--------|------|\n';
            const out = lines.map(line => {
              const m = line.match(/^\|\s*(\d{4}-\d{2}-\d{2})\s*\|\s*(.+?)\s*\|\s*(.*?)\s*\|$/);
              if (!m) return line;
              if (m[1] !== key) return line;
              const status = m[2].trim();
              if (status === '⬜') return `| ${m[1]} | ❌ | Missed |`;
              return line;
            }).join('\n') + '\n';

            md = md.slice(0, s + START_TAG.length) + '\n' + header + out + md.slice(e);
            fs.writeFileSync(readme, md);

      - name: Commit close
        run: |
          git config user.name "actions-bot"
          git config user.email "actions@users.noreply.github.com"
          git add README.md
          git diff --cached --quiet || git commit -m "chore: daily close (mark ❌ for missing)"
          git push
