name: Update Daily Status on Push
on:
  push:
    branches: ['feature/**', 'develop']         # ← develop도 감지하되 직접 커밋은 금지
    paths:
      - '**/solutions/**'
      - '.github/workflows/push_update_status.yml'

permissions:
  contents: write
  pull-requests: write

jobs:
  mark:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Seoul
      START_DATE: '2025-10-02'
      END_DATE: '2025-11-21'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}                # 현재 브랜치 체크아웃

      # README 갱신 JS 스텝 (여기서 process.env.START_DATE 등 사용)

      # feature/* 에서는 "현재 브랜치로" 직접 커밋
      - name: Commit to feature branch
        if: startsWith(github.ref_name, 'feature/')
        run: |
          git config user.name "actions-bot"
          git config user.email "actions@users.noreply.github.com"
          git add README.md
          git diff --cached --quiet || git commit -m "chore: mark daily status from solutions push"
          git push origin HEAD:${{ github.ref_name }}

      # develop 에서는 자동 PR만 열기
      - name: Create PR to develop
        if: github.ref_name == 'develop'
        uses: peter-evans/create-pull-request@v6
        with:
          base: develop
          branch: automation/readme-progress
          title: "chore: update README progress (push trigger)"
          commit-message: "chore: update README progress (push trigger)"
