version: "3.9"

services:
  db:
    image: postgres:16
    container_name: northwind-pg
    env_file: ./.env
    ports:
      - "${PG_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data              # 데이터 영속화
      - ./init:/docker-entrypoint-initdb.d           # 01_grants.psql, 02_load.sh
      - ./northwind.sql:/tmp/northwind.sql:ro        # 덤프 파일
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:8.12
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_PORT}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  pgdata:
  pgadmin-data:
