-- Site   : Programmers
-- Title  : 입양 시각 구하기(2) (LEVEL 4)
-- Link   : https://school.programmers.co.kr/learn/courses/30/lessons/59413
-- Date   : 2026-02-05

-- WITH HOUR_NUM AS (
--     ROW_NUMBER() OVER(
--         PARTITION BY HOUR(DATETIME) ORDER BY DATETIME DESC)
--     FROM ANIMAL_OUTS
-- )
-- SELECT HOUR(DATETIME), COUNT(*) COUNT
-- FROM HOUR_NUM
-- GROUP BY HOUR(DATETIME)
-- ORDER BY HOUR(DATETIME);

-- 시간초과

WITH RECURSIVE HOURS AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM HOURS
    WHERE HOUR < 23
)
SELECT H.HOUR, COUNT(A.DATETIME) AS COUNT
FROM HOURS H
LEFT JOIN ANIMAL_OUTS A ON H.HOUR = HOUR(A.DATETIME)
GROUP BY H.HOUR
ORDER BY H.HOUR;

-- 재귀 CTE 사용