name: Cleanup Automation Branches

on:
  pull_request:
    types:
      - closed

permissions:
  contents: write

jobs:
  cleanup:
    if: >-
      ${{ github.event.pull_request.merged && startsWith(github.event.pull_request.head.ref, 'automation/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Delete merged automation branch
        uses: actions/github-script@v7
        with:
          script: |
            const branch = context.payload.pull_request.head.ref;
            const ref = `heads/${branch}`;
            try {
              await github.rest.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref,
              });
              core.info(`Deleted branch ${ref}`);
            } catch (error) {
              if (error.status === 422) {
                core.warning(`Branch ${ref} already deleted.`);
              } else {
                throw error;
              }
            }
